import { useEffect, useState } from "react";
import { generateKokoRoadmap, loadCachedRoadmap, type KokoRoadmap as KokoRoadmapType } from "@/lib/kokoRoadmap";
import { getChosenCareer } from "@/lib/userState";

const KOKO_PURPLE = "#895AF6";

export const KokoRoadmap = () => {
  const career = getChosenCareer();
  const [roadmap, setRoadmap] = useState<KokoRoadmapType | null>(null);
  const [loading, setLoading] = useState(false);
  const [streaming, setStreaming] = useState("");
  const [err, setErr] = useState<string | null>(null);
  const [hydrated, setHydrated] = useState(false);

  useEffect(() => {
    (async () => {
      const cached = await loadCachedRoadmap(career?.title);
      if (cached) setRoadmap(cached);
      setHydrated(true);
    })();
  }, [career?.title]);

  const onGenerate = async () => {
    if (loading) return;
    setLoading(true);
    setErr(null);
    setStreaming("");
    try {
      const r = await generateKokoRoadmap({ onDelta: (raw) => setStreaming(raw) });
      setRoadmap(r);
    } catch (e) {
      setErr(e instanceof Error ? e.message : "Something went wrong.");
    } finally {
      setLoading(false);
      setStreaming("");
    }
  };

  if (!hydrated) return null;

  return (
    <section
      className="mb-8 rounded-2xl border p-5"
      style={{ borderColor: "rgba(137, 90, 246, 0.25)", background: "rgba(137, 90, 246, 0.04)" }}
    >
      <div className="mb-3 flex items-start justify-between gap-3">
        <div>
          <div className="text-[11px] font-bold tracking-[1.5px]" style={{ color: KOKO_PURPLE }}>
            ✦ KOKO'S 2026 ROADMAP
          </div>
          <h2 className="mt-1 text-[18px] font-bold text-foreground">
            {roadmap?.career || career?.title || "Your career"} — generated by Koko
          </h2>
          {roadmap?.summary && (
            <p className="mt-1 text-[13px] leading-snug text-text2">{roadmap.summary}</p>
          )}
        </div>
        <button
          type="button"
          onClick={onGenerate}
          disabled={loading || !career?.title}
          className="shrink-0 rounded-lg px-3.5 py-2 text-[12px] font-semibold text-white transition-opacity disabled:opacity-50"
          style={{ background: KOKO_PURPLE }}
        >
          {loading ? "Generating…" : roadmap ? "Regenerate" : "Generate roadmap"}
        </button>
      </div>

      {err && (
        <div className="rounded-lg border border-border bg-card px-3 py-2 text-[13px] text-text2">{err}</div>
      )}

      {loading && (
        <div className="rounded-lg border border-border bg-card p-3 text-[12px] leading-[1.6] text-text2">
          <div className="mb-1.5 font-semibold text-foreground">Koko is mapping your journey…</div>
          <pre className="max-h-40 overflow-auto whitespace-pre-wrap font-mono text-[11px] text-text3">
            {streaming.slice(-1200) || "…"}
          </pre>
        </div>
      )}

      {!loading && !roadmap && !err && (
        <div className="rounded-lg border border-dashed border-border bg-card p-4 text-[13px] text-text2">
          Click <strong className="text-foreground">Generate roadmap</strong> and Koko will design a complete,
          industry-current journey for becoming a {career?.title || "professional"} in 2026 — including the AI
          tools you'll actually use along the way.
        </div>
      )}

      {!loading && roadmap?.phases?.length ? (
        <ol className="mt-3 flex flex-col gap-3">
          {roadmap.phases.map((p, i) => (
            <li
              key={i}
              className="rounded-xl border border-border bg-card p-4"
            >
              <div className="flex items-center gap-2">
                <span
                  className="grid h-7 w-7 place-items-center rounded-full text-[11px] font-bold text-white"
                  style={{ background: KOKO_PURPLE }}
                >
                  {String(i + 1).padStart(2, "0")}
                </span>
                <h3 className="text-[15px] font-semibold text-foreground">{p.title}</h3>
              </div>

              <p className="mt-2 text-[13px] leading-[1.6] text-text2">
                <span className="font-semibold text-foreground">Goal:</span> {p.goal}
              </p>

              {p.topics?.length ? (
                <div className="mt-2.5">
                  <div className="text-[11px] font-bold tracking-wide text-text3">TOPICS</div>
                  <div className="mt-1 flex flex-wrap gap-1.5">
                    {p.topics.map((t, j) => (
                      <span
                        key={j}
                        className="rounded-full border border-border bg-bg-elevated px-2.5 py-1 text-[11px] text-foreground"
                      >
                        {t}
                      </span>
                    ))}
                  </div>
                </div>
              ) : null}

              {p.tools?.length ? (
                <div className="mt-2.5">
                  <div className="text-[11px] font-bold tracking-wide text-text3">TOOLS</div>
                  <div className="mt-1 flex flex-wrap gap-1.5">
                    {p.tools.map((t, j) => (
                      <span
                        key={j}
                        className="rounded-full border px-2.5 py-1 text-[11px] font-medium"
                        style={{
                          borderColor: "rgba(137,90,246,0.3)",
                          color: KOKO_PURPLE,
                          background: "rgba(137,90,246,0.08)",
                        }}
                      >
                        {t}
                      </span>
                    ))}
                  </div>
                </div>
              ) : null}

              {p.aiIntegration && (
                <aside
                  className="mt-3 rounded-r-lg p-3 text-[12.5px] leading-[1.6]"
                  style={{
                    borderLeft: `3px solid ${KOKO_PURPLE}`,
                    background: "rgba(137,90,246,0.06)",
                  }}
                >
                  <div className="mb-1 text-[11px] font-bold tracking-wide" style={{ color: KOKO_PURPLE }}>
                    ✦ AI INTEGRATION (2026)
                  </div>
                  <div className="text-foreground">{p.aiIntegration}</div>
                </aside>
              )}

              {p.milestone && (
                <div className="mt-3 rounded-lg border border-border bg-bg-elevated p-3 text-[12.5px] text-foreground">
                  <span className="font-semibold">🏁 Milestone:</span> {p.milestone}
                </div>
              )}
            </li>
          ))}
        </ol>
      ) : null}
    </section>
  );
};
