/* WorthScope — Koko-generated roadmap store.
   This is the single source of truth for the user's roadmap, the missions
   shown on the dashboard, and the missions page. There is no static
   fallback — the roadmap MUST be generated by Koko after the user picks
   a career. */

import { streamKokoChat } from "@/lib/kokoClient";
import { supabase } from "@/integrations/supabase/client";
import { getProfile, getChosenCareer } from "@/lib/userState";
import {
  notifyMissionComplete,
  notifyPhaseUnlocked,
  notifyCareerOpportunitiesUnlocked,
} from "@/lib/notifications";

export type KokoMission = {
  mission_number: number;
  mission_title: string;
  mission_description: string;
  topics: string[];
  tools: string[];
  ai_integration: string;
  real_world_milestone: string;
};

export type KokoPhase = {
  phase_number: number;
  phase_title: string;
  phase_goal: string;
  missions: KokoMission[];
};

export type KokoRoadmap = {
  career_path: string;
  estimated_duration_months: number;
  phases: KokoPhase[];
};

const LS_ROADMAP = "worthscope_koko_roadmap";
const LS_DONE = "worthscope_koko_mission_done";

/* ---------- ID helpers ---------- */
export function missionId(phaseNumber: number, missionNumber: number): string {
  return `p${phaseNumber}_m${missionNumber}`;
}

export function parseMissionId(id: string): { phase: number; mission: number } | null {
  const m = /^p(\d+)_m(\d+)$/.exec(id);
  if (!m) return null;
  return { phase: Number(m[1]), mission: Number(m[2]) };
}

/* ---------- Cache (localStorage) ---------- */
export function loadRoadmap(): KokoRoadmap | null {
  if (typeof window === "undefined") return null;
  const raw = localStorage.getItem(LS_ROADMAP);
  if (!raw) return null;
  try {
    const r = JSON.parse(raw) as KokoRoadmap;
    if (!r?.phases?.length) return null;
    return r;
  } catch {
    return null;
  }
}

function saveRoadmapLocal(r: KokoRoadmap) {
  localStorage.setItem(LS_ROADMAP, JSON.stringify(r));
  window.dispatchEvent(new CustomEvent("worthscope:roadmap"));
}

/* ---------- Completion tracking ---------- */
function loadDone(): Record<string, true> {
  if (typeof window === "undefined") return {};
  try {
    return JSON.parse(localStorage.getItem(LS_DONE) || "{}");
  } catch {
    return {};
  }
}

function saveDone(d: Record<string, true>) {
  localStorage.setItem(LS_DONE, JSON.stringify(d));
  window.dispatchEvent(new CustomEvent("worthscope:roadmap"));
}

export function isMissionCompleted(id: string): boolean {
  return !!loadDone()[id];
}

export function markRoadmapMissionComplete(id: string) {
  const d = loadDone();
  if (d[id]) return; // already done — no duplicate notifications
  d[id] = true;
  saveDone(d);

  // Fire notifications based on the new state (best-effort, never block).
  try {
    const roadmap = loadRoadmap();
    if (!roadmap) return;
    const parsed = parseMissionId(id);
    if (!parsed) return;

    const phase = roadmap.phases.find((p) => p.phase_number === parsed.phase);
    const mission = phase?.missions.find((m) => m.mission_number === parsed.mission);
    if (!mission) return;

    const after = getCurrentMissionRef(roadmap);
    notifyMissionComplete(mission.mission_title, after?.mission.mission_title).catch(() => {});

    const phaseDone = phase && phase.missions.every(
      (m) => loadDone()[missionId(phase.phase_number, m.mission_number)],
    );
    if (phaseDone) {
      const next = roadmap.phases.find((p) => p.phase_number === parsed.phase + 1);
      if (next) notifyPhaseUnlocked(next.phase_title, next.phase_number).catch(() => {});
    }

    if (getOverallProgress(roadmap) >= 70) {
      notifyCareerOpportunitiesUnlocked().catch(() => {});
    }
  } catch (e) {
    console.warn("[kokoRoadmap] notification side-effect failed", e);
  }
}

export function resetRoadmapProgress() {
  if (typeof window === "undefined") return;
  localStorage.removeItem(LS_DONE);
  window.dispatchEvent(new CustomEvent("worthscope:roadmap"));
}

/* ---------- Unlock / status helpers ---------- */
export type MissionStatus = "completed" | "current" | "locked";

export function getMissionStatus(
  roadmap: KokoRoadmap,
  phaseNumber: number,
  missionNumber: number,
): MissionStatus {
  const done = loadDone();
  const id = missionId(phaseNumber, missionNumber);
  if (done[id]) return "completed";

  // Phase 1 mission 1 always unlocked.
  if (phaseNumber === 1 && missionNumber === 1) return "current";

  // Previous mission in same phase must be done.
  if (missionNumber > 1) {
    const prev = missionId(phaseNumber, missionNumber - 1);
    if (done[prev]) return "current";
    return "locked";
  }

  // First mission in a later phase — previous phase must be fully done.
  const prevPhase = roadmap.phases.find((p) => p.phase_number === phaseNumber - 1);
  if (prevPhase && prevPhase.missions.every((m) => done[missionId(prevPhase.phase_number, m.mission_number)])) {
    return "current";
  }
  return "locked";
}

export function getCurrentMissionRef(
  roadmap: KokoRoadmap,
): { phase: KokoPhase; mission: KokoMission } | null {
  for (const p of roadmap.phases) {
    for (const m of p.missions) {
      const s = getMissionStatus(roadmap, p.phase_number, m.mission_number);
      if (s !== "completed") return { phase: p, mission: m };
    }
  }
  return null;
}

export function getCurrentPhase(roadmap: KokoRoadmap): KokoPhase {
  const cur = getCurrentMissionRef(roadmap);
  return cur?.phase || roadmap.phases[0];
}

export function getOverallProgress(roadmap: KokoRoadmap): number {
  const done = loadDone();
  let total = 0;
  let completed = 0;
  for (const p of roadmap.phases) {
    for (const m of p.missions) {
      total++;
      if (done[missionId(p.phase_number, m.mission_number)]) completed++;
    }
  }
  if (!total) return 0;
  return Math.round((completed / total) * 100);
}

export function getPhaseProgress(roadmap: KokoRoadmap, phaseNumber: number): { completed: number; total: number; pct: number } {
  const done = loadDone();
  const phase = roadmap.phases.find((p) => p.phase_number === phaseNumber);
  if (!phase) return { completed: 0, total: 0, pct: 0 };
  const total = phase.missions.length;
  const completed = phase.missions.filter((m) => done[missionId(phase.phase_number, m.mission_number)]).length;
  return { completed, total, pct: total ? Math.round((completed / total) * 100) : 0 };
}

export function isPhaseLocked(roadmap: KokoRoadmap, phaseNumber: number): boolean {
  if (phaseNumber === 1) return false;
  const prev = roadmap.phases.find((p) => p.phase_number === phaseNumber - 1);
  if (!prev) return false;
  const done = loadDone();
  return !prev.missions.every((m) => done[missionId(prev.phase_number, m.mission_number)]);
}

/* ---------- Server load / save ---------- */
export async function loadCachedRoadmap(career?: string | null): Promise<KokoRoadmap | null> {
  // Prefer local first.
  const local = loadRoadmap();
  if (local) return local;

  const { data: u } = await supabase.auth.getUser();
  if (!u.user) return null;
  let q = supabase.from("koko_roadmaps").select("roadmap_json").eq("user_id", u.user.id);
  if (career) q = q.eq("career", career);
  const { data } = await q.maybeSingle();
  const r = (data?.roadmap_json as KokoRoadmap | null) || null;
  if (r?.phases?.length) {
    saveRoadmapLocal(r);
    return r;
  }
  return null;
}

/* ---------- JSON extraction ---------- */
function extractJson(raw: string): KokoRoadmap | null {
  const cleaned = raw.replace(/^```(?:json)?/i, "").replace(/```$/i, "").trim();
  const start = cleaned.indexOf("{");
  const end = cleaned.lastIndexOf("}");
  if (start < 0 || end <= start) return null;
  try {
    const obj = JSON.parse(cleaned.slice(start, end + 1));
    if (!obj || !Array.isArray(obj.phases)) return null;
    // Light normalisation in case the model nests slightly differently.
    obj.phases = obj.phases.map((p: any, i: number) => ({
      phase_number: Number(p.phase_number ?? i + 1),
      phase_title: String(p.phase_title ?? p.title ?? `Phase ${i + 1}`),
      phase_goal: String(p.phase_goal ?? p.goal ?? ""),
      missions: Array.isArray(p.missions)
        ? p.missions.map((m: any, j: number) => ({
            mission_number: Number(m.mission_number ?? j + 1),
            mission_title: String(m.mission_title ?? m.title ?? `Mission ${j + 1}`),
            mission_description: String(m.mission_description ?? m.description ?? ""),
            topics: Array.isArray(m.topics) ? m.topics.map(String) : [],
            tools: Array.isArray(m.tools) ? m.tools.map(String) : [],
            ai_integration: String(m.ai_integration ?? m.aiIntegration ?? ""),
            real_world_milestone: String(m.real_world_milestone ?? m.milestone ?? ""),
          }))
        : [],
    }));
    obj.career_path = String(obj.career_path ?? obj.career ?? "");
    obj.estimated_duration_months = Number(obj.estimated_duration_months ?? 6);
    return obj as KokoRoadmap;
  } catch {
    return null;
  }
}

/* ---------- Generate + persist ---------- */
export async function generateKokoRoadmap(opts?: {
  onDelta?: (raw: string) => void;
  resetProgress?: boolean;
}): Promise<KokoRoadmap> {
  const profile = getProfile();
  const career = getChosenCareer();
  if (!career?.title) throw new Error("No career chosen yet.");

  let raw = "";
  await new Promise<void>((resolve, reject) => {
    streamKokoChat({
      messages: [],
      intent: "roadmap",
      mission: {
        career: career.title,
        userName: profile?.firstName,
        userAge: typeof profile?.age === "number" ? profile.age : undefined,
        educationLevel: profile?.educationLevel || undefined,
      },
      onDelta: (c) => {
        raw += c;
        opts?.onDelta?.(raw);
      },
      onDone: () => resolve(),
      onError: (e) => reject(e),
    });
  });

  const parsed = extractJson(raw);
  if (!parsed) throw new Error("Koko returned an invalid roadmap.");

  if (!parsed.career_path) parsed.career_path = career.title;

  // Reset progress if requested (e.g. retaking the assessment).
  if (opts?.resetProgress) resetRoadmapProgress();

  saveRoadmapLocal(parsed);

  const { data: u } = await supabase.auth.getUser();
  if (u.user) {
    await supabase.from("koko_roadmaps").upsert(
      {
        user_id: u.user.id,
        career: career.title,
        roadmap_json: parsed as unknown as never,
      },
      { onConflict: "user_id,career" },
    );
  }
  return parsed;
}
