project_id = "iftqcqpbcioyzrhqvgvc"

[functions.koko-chat]
verify_jwt = false

[functions.koko-youtube]
verify_jwt = false

[functions.jobs-fetch]
verify_jwt = false

[functions.koko-voice-session]
verify_jwt = false
